src/Entity/PlanningMedecins.php
<?php


namespace App\Entity;


use App\Repository\PlanningMedecinsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: PlanningMedecinsRepository::class)]
class PlanningMedecins
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 255)]
    private ?string $jour_debut = null;


    #[ORM\Column(length: 255)]
    private ?string $jour_fin = null;


    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_debut = null;


    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_fin = null;


    #[ORM\Column]
    private ?bool $disponibilite = null;


   


    #[ORM\ManyToOne(inversedBy: 'planningMedecins')]
    private ?User $user = null;


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getJourDebut(): ?string
    {
        return $this->jour_debut;
    }


    public function setJourDebut(string $jour_debut): static
    {
        $this->jour_debut = $jour_debut;


        return $this;
    }


    public function getJourFin(): ?string
    {
        return $this->jour_fin;
    }


    public function setJourFin(string $jour_fin): static
    {
        $this->jour_fin = $jour_fin;


        return $this;
    }


    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }


    public function setHeureDebut(\DateTimeInterface $heure_debut): static
    {
        $this->heure_debut = $heure_debut;


        return $this;
    }


    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }


    public function setHeureFin(\DateTimeInterface $heure_fin): static
    {
        $this->heure_fin = $heure_fin;


        return $this;
    }


    public function isDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }


    public function setDisponibilite(bool $disponibilite): static
    {
        $this->disponibilite = $disponibilite;


        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }


    public function setUser(?User $user): static
    {
        $this->user = $user;


        return $this;
    }
}

src/Form/PlanningMedecinsType.php
<?php

namespace App\Form;

use App\Entity\PlanningMedecins;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;



class PlanningMedecinsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('jour_debut', ChoiceType::class, [
            'choices' => [
                'Lundi' => 'Lundi',
                'Mardi' => 'Mardi',
                'Mercredi' => 'Mercredi',
                'Jeudi' => 'Jeudi',
                'Vendredi' => 'Vendredi',
                'Samedi' => 'Samedi',
                'Dimanche' => 'Dimanche',
            ],
            'constraints' => [
                new Choice([
                    'choices' => ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
                    'message' => 'Veuillez choisir un jour valide de la semaine.',
                ]),
            ],
        ])
        ->add('jour_fin', ChoiceType::class, [
            'choices' => [
                'Lundi' => 'Lundi',
                'Mardi' => 'Mardi',
                'Mercredi' => 'Mercredi',
                'Jeudi' => 'Jeudi',
                'Vendredi' => 'Vendredi',
                'Samedi' => 'Samedi',
                'Dimanche' => 'Dimanche',
            ],
            'constraints' => [
                new Choice([
                    'choices' => ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
                    'message' => 'Veuillez choisir un jour valide de la semaine.',
                ]),
            ],
        ])
           
            ->add('heure_debut')
            ->add('heure_fin')
            ->add('disponibilite')
            
           
           

            ->add('User', EntityType::class, [
                'class' => User::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->andWhere('u.role = :role')
                        ->setParameter('role', 'medecin');
                },
           
            ])





        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PlanningMedecins::class,
        ]);
    }
}

src/Controller/PlanningMedecinsController.php
<?php

namespace App\Controller;

use App\Entity\PlanningMedecins;
use App\Form\PlanningMedecinsType;
use App\Repository\PlanningMedecinsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/p')]
class PlanningMedecinsController extends AbstractController
{
    #[Route('/', name: 'app_planning_medecins_index', methods: ['GET'])]
    public function index(PlanningMedecinsRepository $planningMedecinsRepository): Response
    {
        return $this->render('planning_medecins/index.html.twig', [
            'planning_medecins' => $planningMedecinsRepository->findAll(),
        ]);
    }

    #[Route('/back', name: 'app_planning_medecins_indedxdza', methods: ['GET'])]
    public function index21(PlanningMedecinsRepository $planningMedecinsRepository): Response
    {
        return $this->render('planning_medecins/backplan.html.twig', [
            'planning_medecins' => $planningMedecinsRepository->findAll(),
        ]);
    }


    #[Route('/affiche', name: 'app_planning_medecins_index1', methods: ['GET'])]
    public function index1(PlanningMedecinsRepository $planningMedecinsRepository): Response
    {
        return $this->render('planning_medecins/Pfront.html.twig', [
            'p' => $planningMedecinsRepository->findAll(),
        ]);
    }






    #[Route('/new', name: 'app_planning_medecins_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $planningMedecin = new PlanningMedecins();
        $form = $this->createForm(PlanningMedecinsType::class, $planningMedecin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($planningMedecin);
            $entityManager->flush();

            return $this->redirectToRoute('app_planning_medecins_indedxdza', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('planning_medecins/new.html.twig', [
            'planning_medecin' => $planningMedecin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planning_medecins_show', methods: ['GET'])]
    public function show(PlanningMedecins $planningMedecin): Response
    {
        return $this->render('planning_medecins/show.html.twig', [
            'planning_medecin' => $planningMedecin,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_planning_medecins_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PlanningMedecins $planningMedecin, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlanningMedecinsType::class, $planningMedecin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_planning_medecins_indedxdza', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('planning_medecins/edit.html.twig', [
            'planning_medecin' => $planningMedecin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planning_medecins_delete', methods: ['POST'])]
    public function delete(Request $request, PlanningMedecins $planningMedecin, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$planningMedecin->getId(), $request->request->get('_token'))) {
            $entityManager->remove($planningMedecin);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_planning_medecins_indedxdza', [], Response::HTTP_SEE_OTHER);
    }
}

templates/planning_medecins/Pfront.html.twig
{% extends 'base.html.twig' %}



{% block body %}
  <!-- Header Start -->
  <div class="bradcam_area breadcam_bg">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Planning medecin</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>






 

 
 <br>
 

 








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Réservation de rendez-vous</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: center;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        .available {
            background-color: #aaffaa;
        }

        .reserved {
            background-color: #ffaaaa;
        }
    </style>
</head>
<body>

<h2>Calendrier de réservation</h2>

<table>
   
   
   
    <tr>
       <th>Nom Medecin</th>
        <th>disponibilité</th>
       
        
        
    </tr>
    
    {% for planning_medecin in p %}
    
                   
          
    <tr>
         <td>{{ planning_medecin.User }}</td>
       
          


           {% if planning_medecin.disponibilite == 1 %}
        
        
        
           <td class="available"><a href="http://127.0.0.1:8000/calendar/new">Disponible</a></td>
    
           {% else %}
        
        
             <td class="reserved">Réservé</td>
   
         {% endif %} 
   
   
    </tr>
    
                


              
     {% endfor %} 
    <!-- Ajoutez d'autres lignes pour les autres jours -->
</table>















</body>
</html>








<br>




 




 <!-- form itself end-->
    <form id="test-form" class="white-popup-block mfp-hide">
        <div class="popup_box ">
            <div class="popup_inner" href="./index.html">
              
              
              
                <h3>
    <a href="http://127.0.0.1:8000/calendar/new">Book an <span>Appointment</span></a>
</h3>
               
            </div>
        </div>
    </form>
    <!-- form itself end -->




  {% endblock %}

templates/planning_medecins/_delete_form.html.twig
<form method="post" action="{{ path('app_planning_medecins_delete', {'id': planning_medecin.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planning_medecin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/planning_medecins/backplan.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg" viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run composer require symfony/webpack-encore-bundle to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
{% block body %}









<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Modernize Free</title>
  <link rel="shortcut icon" type="image/png" href="../assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="../assets/css/styles.min.css" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="./index.html" class="text-nowrap logo-img">
            <img src="../assets/images/logos/dark-logo.svg" width="180" alt="" />
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
       <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Home</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./index.html" aria-expanded="false">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu">Dashboard</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Management</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./ui-buttons.html" aria-expanded="false">
                <span>
                  <i class="ti ti-user"></i>
                </span>
                <span class="hide-menu">Users</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="http://127.0.0.1:8000/medicament/b" aria-expanded="false">
                <span>
                  <i class="ti ti-rss"></i>
                </span>
                <span class="hide-menu">Medications</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="http://127.0.0.1:8000/prescriptions/" aria-expanded="false">
                <span>
                  <i class="ti ti-receipt"></i>
                </span>
                <span class="hide-menu">Prescriptions</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="http://127.0.0.1:8000/calendar/back" aria-expanded="false">
                <span>
                  <i class="ti ti-reload"></i>
                </span>
                <span class="hide-menu">Appointments</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="http://127.0.0.1:8000/c" aria-expanded="false">
                <span>
                  <i class="ti ti-calendar"></i>
                </span>
                <span class="hide-menu">Doctor plannings</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./ui-typography.html" aria-expanded="false">
                <span>
                  <i class="ti ti-star"></i>
                </span>
                <span class="hide-menu">Feedback</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./ui-typography.html" aria-expanded="false">
                <span>
                  <i class="ti ti-clipboard"></i>
                </span>
                <span class="hide-menu">Feedback Responses</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="" aria-expanded="false">
                <span>
                  <i class="ti ti-article"></i>
                </span>
                <span class="hide-menu">Articles</span>
              </a>
              
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="" aria-expanded="false">
                <span>
                  <i class="ti ti-pencil"></i>
                </span>
                <span class="hide-menu">Comments</span>
              </a>
            </li>
           
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper">
      <!--  Header Start -->
       <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                <i class="ti ti-bell-ringing"></i>
                <div class="notification bg-primary rounded-circle"></div>
              </a>
            </li>
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              <a href="https://adminmart.com/product/modernize-free-bootstrap-admin-dashboard/" target="_blank" class="btn btn-primary">Download Free</a>
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <img src="../assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                  <div class="message-body">
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-user fs-6"></i>
                      <p class="mb-0 fs-3">My Profile</p>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-mail fs-6"></i>
                      <p class="mb-0 fs-3">My Account</p>
                    </a>
                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                      <i class="ti ti-list-check fs-6"></i>
                      <p class="mb-0 fs-3">My Task</p>
                    </a>
                    <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!--  Header End -->
       
          
                  <br>
                    <br>
                      <br>
                        <br>
                  
                    </thead>
                    <tbody>
                          <h1>Table planning medecin</h1>

    <table class="table">
        <thead>
            <tr>
                <th>medecin</th>
                <th>jour_debut</th>
                <th>jour_fin</th>
                <th>heure_debut</th>
                <th>heure_fin</th>
                <th>disponibilite</th>
              
             
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for planning_medecin in planning_medecins %}
            <tr>
                <td>{{ planning_medecin.User }}</td>
                <td>{{ planning_medecin.jourDebut }}</td>
                <td>{{ planning_medecin.jourFin }}</td>
                <td>{{ planning_medecin.heureDebut ? planning_medecin.heureDebut|date('H:i:s') : '' }}</td>
                <td>{{ planning_medecin.heureFin ? planning_medecin.heureFin|date('H:i:s') : '' }}</td>
                <td>{{ planning_medecin.disponibilite ? 'Yes' : 'No' }}</td>
                <td>
                     <a href="http://127.0.0.1:8000/p/back"> {{ include('planning_medecins/_delete_form.html.twig') }}</a>
                    <a href="{{ path('app_planning_medecins_edit', {'id': planning_medecin.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

                <a href="http://127.0.0.1:8000/p/new"> new planning medecin</a>                       
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
       
          </div>
        </div>
        <div class="py-6 px-6 text-center">
         
        </div>
      </div>
    </div>
  </div>
  <script src="../assets/libs/jquery/dist/jquery.min.js"></script>
  <script src="../assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="../assets/js/sidebarmenu.js"></script>
  <script src="../assets/js/app.min.js"></script>
  <script src="../assets/libs/apexcharts/dist/apexcharts.min.js"></script>
  <script src="../assets/libs/simplebar/dist/simplebar.js"></script>
  <script src="../assets/js/dashboard.js"></script>
</body>

</html>

























{% endblock %}
</body>
</html>

templates/planning_medecins/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlanningMedecins index{% endblock %}

{% block body %}
 <div class="bradcam_area breadcam_bg">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>planning</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h1>PlanningMedecins index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Jour_debut</th>
                <th>Jour_fin</th>
                <th>Heure_debut</th>
                <th>Heure_fin</th>
                <th>Disponibilite</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for planning_medecin in planning_medecins %}
            <tr>
                <td>{{ planning_medecin.id }}</td>
                <td>{{ planning_medecin.jourDebut }}</td>
                <td>{{ planning_medecin.jourFin }}</td>
                <td>{{ planning_medecin.heureDebut ? planning_medecin.heureDebut|date('H:i:s') : '' }}</td>
                <td>{{ planning_medecin.heureFin ? planning_medecin.heureFin|date('H:i:s') : '' }}</td>
                <td>{{ planning_medecin.disponibilite ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_planning_medecins_show', {'id': planning_medecin.id}) }}">show</a>
                    <a href="{{ path('app_planning_medecins_edit', {'id': planning_medecin.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_planning_medecins_new') }}">Create new</a>
{% endblock %}

templates/planning_medecins/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}PlanningMedecins{% endblock %}

{% block body %}
    
    <div class="bradcam_area breadcam_bg">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>prescription</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    
    
    <h1>PlanningMedecins</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ planning_medecin.id }}</td>
            </tr>
            <tr>
                <th>Jour_debut</th>
                <td>{{ planning_medecin.jourDebut }}</td>
            </tr>
            <tr>
                <th>Jour_fin</th>
                <td>{{ planning_medecin.jourFin }}</td>
            </tr>
            <tr>
                <th>Heure_debut</th>
                <td>{{ planning_medecin.heureDebut ? planning_medecin.heureDebut|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Heure_fin</th>
                <td>{{ planning_medecin.heureFin ? planning_medecin.heureFin|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Disponibilite</th>
                <td>{{ planning_medecin.disponibilite ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_planning_medecins_index') }}">back to list</a>

    <a href="{{ path('app_planning_medecins_edit', {'id': planning_medecin.id}) }}">edit</a>

    {{ include('planning_medecins/_delete_form.html.twig') }}
{% endblock %}